# Generated by Django 3.2.16 on 2022-10-06 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221005_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='government_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='7847', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
